### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by kinverarity1** [GeoStat-Framework/welltestpy#2]
Hey - I have been having trouble running the example code at 02_estimate.py. I get this error:

```
runfile('F:/Python_Examples/welltestpy-master/examples/02_estimate.py', wdir='F:/Python_Examples/welltestpy-master/examples')
Initializing the  Shuffled Complex Evolution (SCE-UA) algorithm  with  5000  repetitions
The objective function will be minimized
Starting burn-in sampling...
Exception in thread Thread-7:
Traceback (most recent call last):
  File "c:\devapps\python\miniconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\devapps\python\miniconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\devapps\python\miniconda3\lib\site-packages\spotpy\algorithms\_algorithm.py", line 446, in model_layer
    q.put(self.setup.simulation(self.partype(*all_params)))
  File "c:\devapps\python\miniconda3\lib\site-packages\welltestpy\estimate\spotpy_classes.py", line 516, in simulation
    ret = self.sim(**self.simkwargs)
  File "c:\devapps\python\miniconda3\lib\site-packages\welltestpy\estimate\spotpy_classes.py", line 167, in function
    rinf=rinf,
TypeError: theis() got an unexpected keyword argument 'T'

Traceback (most recent call last):

  File "<ipython-input-7-e952cc5dfd05>", line 1, in <module>
    runfile('F:/Python_Examples/welltestpy-master/examples/02_estimate.py', wdir='F:/Python_Examples/welltestpy-master/examples')

  File "c:\devapps\python\miniconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "c:\devapps\python\miniconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "F:/Python_Examples/welltestpy-master/examples/02_estimate.py", line 14, in <module>
    estname="estimation.txt",

  File "c:\devapps\python\miniconda3\lib\site-packages\welltestpy\estimate\estimatelib.py", line 949, in run
    sampler.sample(rep, ngs=10, kstop=100, pcento=1e-4, peps=1e-3)

  File "c:\devapps\python\miniconda3\lib\site-packages\spotpy\algorithms\sceua.py", line 186, in sample
    like = self.postprocessing(icall, randompar, simulations,chains=0)

  File "c:\devapps\python\miniconda3\lib\site-packages\spotpy\algorithms\_algorithm.py", line 406, in postprocessing
    like = self.getfitness(simulation=simulation, params=params)

  File "c:\devapps\python\miniconda3\lib\site-packages\spotpy\algorithms\_algorithm.py", line 432, in getfitness
    return self.setup.objectivefunction(evaluation=self.evaluation, simulation=simulation)

  File "c:\devapps\python\miniconda3\lib\site-packages\welltestpy\estimate\spotpy_classes.py", line 528, in objectivefunction
    evaluation=evaluation, simulation=simulation

  File "c:\devapps\python\miniconda3\lib\site-packages\spotpy\objectivefunctions.py", line 252, in rmse
    if len(evaluation) == len(simulation) > 0:

TypeError: object of type 'NoneType' has no len()
```

Any ideas?

**Comment by kinverarity1** [comment]
Actually, this is no longer a problem. The issues were fixed with PRs #1 and #2, and the rest was a buggy package installation on our end.

**Comment by MuellerSeb** [comment]
Hey Kent,

I am sorry for the inconvenience.
welltestpy is still under development in a 0.x status. Therefore things like these still happen. AnaFlow will get a 1.0 release soon, then the interface will settle.

The example and Readme was still in line with [AnaFlow 0.4](https://github.com/GeoStat-Framework/AnaFlow/tree/v0.4.0).

There will be changes within the next month. Maybe you can have another look then. It's always good to get feedback! ;-)

Cheers,
Sebastian

**Comment by kinverarity1** [comment]
Not a problem, thanks for these great packages! After posting this issue I looked at the readme and discovered that things were just shifting around ;-)

**Comment by MuellerSeb** [comment]
@kinverarity1 : You can now have a look at the new [example gallery](https://geostat-framework.readthedocs.io/projects/welltestpy/en/stable/examples/index.html)

**Comment by kinverarity1** [comment]
Thanks! It looks really good, thanks for updating everything. I will let my colleagues now and have a play around 😀
